name: CI/CD Pipeline for Django with Docker

on:
  push:
    branches:
      - main  # Change this to your main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # Change this to your required Python version

    - name: Log in to DockerHub
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: |
        docker build -t my-django-app .

    - name: Push Docker image to DockerHub
      run: |
        docker tag my-django-app ${{ secrets.DOCKER_USERNAME }}/my-django-app:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/my-django-app:latest

    - name: Deploy to EC2
      env:
        EC2_HOST: ${{ secrets.EC2_HOST }}
        EC2_USER: ${{ secrets.EC2_USER }}
        EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
        DOCKER_IMAGE: ${{ secrets.DOCKER_USERNAME }}/my-django-app:latest
      run: |
        # Create a temporary SSH key file
        echo "${{ secrets.EC2_SSH_KEY }}" > private_key.pem
        chmod 600 private_key.pem

        # SSH into the EC2 instance and deploy
        ssh -o StrictHostKeyChecking=no -i private_key.pem ${EC2_USER}@${EC2_HOST} << 'EOF'
          # Update Docker image and restart the container
          docker pull $DOCKER_IMAGE
          docker stop my-django-container || true
          docker rm my-django-container || true
          docker run -d --name my-django-container -p 8000:8000 \
            -e DJANGO_SETTINGS_MODULE=myproject.settings \
            $DOCKER_IMAGE
        EOF
